#!/bin/bash

echo "Starting Auto Update script..."

# # Set current directory and install requirements

# Is python pre-installed?
echo "Installing dependencies..."
python3 -m venv .venv
source .venv/bin/activate
pip install -r source/requirements.txt
pip install illuminator --no-deps

# For some reason it behaves as if illuminator does not exist
echo "Building sphinx documentation..."
# Very odd behaviour. Building once creates warnings, building twice doesnt.
sphinx-build ./source ./docs 
sphinx-build ./source ./docs --fail-on-warning



